### PR TITLE
Add the ability to use a rxode2 function (which helps with imported models or getting results from a nlmixr2 fit).

### PR DESCRIPTION
**Pull request by mattfidler**
This takes the information from #46 to build the list for the `posologyr` model.

### CODE REVIEW

**Comment by mattfidler** [comment]
For example:

``` r
library(posologyr)
patient_data <- data.frame(ID=1,
                           TIME=c(0.0,1.0,14.0),
                           DV=c(NA,25.0,5.5),
                           AMT=c(2000,0,0),
                           DUR=c(0.5,NA,NA),
                           EVID=c(1,0,0),
                           CLCREAT=80,
                           WT=65)

mod_run001 <- function() {
  ini({
    THETA_Cl <- 4.0
    THETA_Vc <- 70.0
    THETA_Ka <- 1.0
    ETA_Cl ~ 0.2
    ETA_Vc ~ 0.2
    ETA_Ka ~ 0.2
    prop.sd <- sqrt(0.05)
  })
  model({
    TVCl <- THETA_Cl
    TVVc <- THETA_Vc
    TVKa <- THETA_Ka

    Cl <- TVCl*exp(ETA_Cl)
    Vc <- TVVc*exp(ETA_Vc)
    Ka <- TVKa*exp(ETA_Ka)

    K20 <- Cl/Vc
    Cc <- centr/Vc

    d/dt(depot) = -Ka*depot
    d/dt(centr) = Ka*depot - K20*centr
    Cc ~ prop(prop.sd)
  })
}

f <- poso_estim_map(patient_data, mod_run001)

f
#> $eta
#>     ETA_Cl     ETA_Vc     ETA_Ka 
#>  0.6019036 -0.4291734  0.1278473 
#> 
#> $model
#> ── Solved rxode2 object ──
#> ── Parameters ($params): ──
#>   THETA_Cl   THETA_Vc   THETA_Ka    prop.sd     ETA_Cl     ETA_Vc     ETA_Ka 
#>  4.0000000 70.0000000  1.0000000  0.2236068  0.6019036 -0.4291734  0.1278473 
#> ── Initial Conditions ($inits): ──
#> depot centr   AUC 
#>     0     0     0 
#> ── First part of data (object): ──
#> # A tibble: 151 × 13
#>    time  TVCl  TVVc  TVKa    Cl    Vc    Ka   K20   rxCc     Cc depot centr
#>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl> <dbl> <dbl>
#> 1   0       4    70     1  7.30  45.6  1.14 0.160  0      0        0    0  
#> 2   0.1     4    70     1  7.30  45.6  1.14 0.160  0.478  0.478  378.  21.8
#> 3   0.2     4    70     1  7.30  45.6  1.14 0.160  1.83   1.83   716.  83.5
#> 4   0.3     4    70     1  7.30  45.6  1.14 0.160  3.95   3.95  1017. 180. 
#> 5   0.4     4    70     1  7.30  45.6  1.14 0.160  6.75   6.75  1286. 307. 
#> 6   0.5     4    70     1  7.30  45.6  1.14 0.160 10.1   10.1   1526. 461. 
#> # ℹ 145 more rows
#> # ℹ 1 more variable: AUC <dbl>
#> 
#> $event
#>      id time  amt evid dur
#>   1:  1  0.0   NA    0  NA
#>   2:  1  0.0 2000    1 0.5
#>   3:  1  0.1   NA    0  NA
#>   4:  1  0.2   NA    0  NA
#>   5:  1  0.3   NA    0  NA
#>  ---                      
#> 148:  1 14.6   NA    0  NA
#> 149:  1 14.7   NA    0  NA
#> 150:  1 14.8   NA    0  NA
#> 151:  1 14.9   NA    0  NA
#> 152:  1 15.0   NA    0  NA
```

<sup>Created on 2023-12-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mattfidler** [comment]
I have reproduced your vignettes as well.

Since it appears that some of the functions are random number based (which makes sense), I would suggest setting a seed before running these functions.

**Comment by mattfidler** [comment]
This passes `::check()` but I see:

```
─  checking tests
    [1923s/270s] OK

   * checking re-building of vignette outputs ... [1680s/229s] OK
```

To fix this if you want to take this to CRAN you probably need to add:

```r
library(rxode2)
library(testthat)
setRxThreads(1L)
test_check("rxode2")
```

**Comment by levenc** [comment]
Thanks a lot for your great work. I'm sure it will be useful to posologyr users. Writing or transcribing a model can be daunting, and rxode2's syntax is crystal clear.

And thanks for the tip about CRAN, I'll use that.

**Comment by mattfidler** [comment]
You probably need to throttle threads for data table too.  You could possibly expand this to lognormal and power models without too much effort, but I think this covers most of the important cases (except perhaps lognomral)

**Pull request merged**
